### ISSUE TITLE
Add Connection class

### ISSUE THREAD

**Issue by danielbachhuber** [WP-API/client-php#3]
Passing username and password to `WPAPI` is lame. We should have proper connection class(es), with oAuth1 and Basic_Auth to start.

**Comment by rmccue** [comment]
This is what Requests_Auth is for, I'd like to avoid another layer of indirection there. We can actually store a serialised version of the object for use between requests too.

**Comment by rmccue** [comment]
Closing, we can just use `Requests_Auth`.
